# xtreemfs docker images

dir:
  image: xtreemfs/xtreemfs-common
  net: "host"
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30638:30638"
    - "32638:32638"
  command: dir

mrc:
  image: xtreemfs/xtreemfs-common
  net: "host"
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30636:30636"
    - "32636:32636"
  command: mrc

osd:
  image: xtreemfs/xtreemfs-common
  net: "host"
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30640:30640"
    - "32640:32640"
  command: osd
